server:
  port: 8080

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/acg_mooc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: 
    password: 


# 应该没有
#mybatis:
 # mapper-locations:
  #  - classpath*:com/**/mapper/*.xml

