server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: 
    password: 
  servlet:
    multipart:
        max-file-size: 500MB
        max-request-size: 500MB
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

# 自定义redis key
redis:
 key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间



mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId:  # 访问身份验证中用到用户标识
    accessKeySecret:  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName:  # oss的存储空间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: # Bearer  #JWT负载中拿到开头



QQemail:
      msm:
        mail:  #邮箱号
  # host
        host: smtp.qq.com
  # 端口 587和465都可以
        port: 465
  # 发送短信的密码
        password: # f**k！ 这玩意不是qq密码 是开启smtp的密码！